### PR TITLE
Upgrade to angular 12

### PR DESCRIPTION
**Pull request by Jakob-em**
<details>
  <summary>📦 Published PR as canary version: <code>1.2.0--canary.5.78804d7.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install storybook-addon-angular-router@1.2.0--canary.5.78804d7.0
  # or 
  yarn add storybook-addon-angular-router@1.2.0--canary.5.78804d7.0
  ```
</details>

### CODE REVIEW

**Comment by kingjordan** [comment]
this does not work in my angular 12 project, it is inside an nx workspace.
```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @storybook/addons@6.2.9
npm ERR! node_modules/@storybook/addons
npm ERR!   @storybook/addons@"6.2.9" from @storybook/addon-knobs@6.2.9
npm ERR!   node_modules/@storybook/addon-knobs
npm ERR!     dev @storybook/addon-knobs@"^6.2.7" from the root project
npm ERR!   @storybook/addons@"6.2.9" from @storybook/client-api@6.2.9
npm ERR!   node_modules/@storybook/addon-knobs/node_modules/@storybook/client-api
npm ERR!     @storybook/client-api@"6.2.9" from @storybook/addon-knobs@6.2.9
npm ERR!     node_modules/@storybook/addon-knobs
npm ERR!       dev @storybook/addon-knobs@"^6.2.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev storybook-addon-angular-router@"1.1.2--canary.5.c63dfd9.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @storybook/addons@6.3.0-beta.8
npm ERR! node_modules/@storybook/addons
npm ERR!   peer @storybook/addons@"^6.3.0-alpha.33" from storybook-addon-angular-router@1.1.2--canary.5.c63dfd9.0
npm ERR!   node_modules/storybook-addon-angular-router
npm ERR!     dev storybook-addon-angular-router@"1.1.2--canary.5.c63dfd9.0" from the root 
project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jorda\AppData\Local\npm-cache\eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jorda\AppData\Local\npm-cache\_logs\2021-06-02T13_26_22_192Z-debug.log
```

**Comment by kingjordan** [comment]
if i extract your source code into an isolated story it works, its just a dependency issue, i think it is a result of storybook 6 not working with angular 12, so we had to use a beta of storybook to get it working

**Comment by Jakob-em** [comment]
@kingjordan Yes the problems are not related to the addon code itself but to the compatibility of storybook with angular 12.
I will release a new version with the correct dependencies once storybook 6.3 is released.

**Comment by Jakob-em** [comment]
@kingjordan I just released version 1.3.0 which should work with angular 12 and storybook 6.3.0 🎊

**Pull request merged**
